### ISSUE TITLE
Basic TacoShack Support

### ISSUE THREAD

**Issue by hakiobo** [hakiobo/LXVBot#3]
LXV Bot needs to be able to support the following reminders for tacoshack

- [x] Tip
- [x] Work
- [x] Overtime
- [x] Buying Boosts
- [x] Daily
- [x] Cleaning

**Comment by BloomJr** [comment]
Close this Issue when.

**Comment by hakiobo** [comment]
Addressed with c3f2907275c7d826425114f41d9cdaff5d3260bf
