### ISSUE TITLE
Handle Star/Heart Roles from Mee6 Bot levels

### ISSUE THREAD

**Issue by hakiobo** [hakiobo/LXVBot#6]
LXV Bot should be able to auto assign/remove the relevant star/heart roles from people based on Mee6 level up messages so that staff doesn't need to handle it manually

**Comment by hakiobo** [comment]
Added with d27827c7797f69539c1d0ec6f0b56c24450876fd

**Comment by BloomJr** [comment]
Ah yes taking one job out from staff, time to be lazy :Paul:
